apiVersion: v1
kind: Service
metadata:
  name: kubeblog
spec:
  selector:
    app: kubeblog
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeblog
spec:
  selector:
    matchLabels:
      app: kubeblog
  template:
    metadata:
      labels:
        app: kubeblog
    spec:
      hostAliases:
      - ip: "119.91.113.111"
        hostnames:
        - "art.local"
      containers:
      - name: kubeblog
        image: 119.91.113.111:8081/docker-local/kubeblog:1.0
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_PORT
            value: "30306"
          - name: MYSQL_SERVER
            value: "192.168.0.129"
      imagePullSecrets:
      - name: regcred-local
