apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  completions: 5
  template:
    # 这里是 Pod 模版
    spec:
      containers:
        - name: hello
          image: nginx
          command: ['sh', '-c', 'echo "Hello, Kubernetes! " && sleep 2']
      restartPolicy: OnFailure
    # 以上为 Pod 模版
