apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  ports:
    - port: 80
      name: nginx-service80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx
  type: NodePort
