apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: registry.cn-beijing.aliyuncs.com/google_registry/perl:5.26
          command: [ "perl",  "-Mbignum=bpi", "-wle", "print bpi(100)" ]
      restartPolicy: Never
  backoffLimit: 4
